# Generated by Django 3.2 on 2021-04-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210419_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bad',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='低評価'),
        ),
        migrations.AlterField(
            model_name='video',
            name='badtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='good',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='高評価'),
        ),
        migrations.AlterField(
            model_name='video',
            name='goodtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
    ]
