# Generated by Django 3.2 on 2021-04-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210420_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='低評価'),
        ),
        migrations.AlterField(
            model_name='video',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='高評価'),
        ),
    ]
