Rails.application.routes.draw do
  get 'cards/index'
  get 'cards/show'
  get 'cards/add'
  get 'cards/edit'
  get 'people/index'
  get 'people', to: 'people#index'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/:id', to: 'people#show'
  get 'people/edit/:id', to: 'people#edit'
  get 'people/delete/:id', to: 'people#delete'
  patch 'people/edit/:id', to: 'people#update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index'
  get 'hello', to: 'hello#index'
  get 'hello/other'
  post 'hello', to: 'hello#index'
  post 'hello/index'
  get 'msgboard/index'
  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'
  post 'msgboard/index'
end
