# Generated by Django 3.1.7 on 2021-03-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210331_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='categorys',
            new_name='category',
        ),
    ]
