# Generated by Django 3.1.7 on 2021-03-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewsConfig',
            new_name='Review',
        ),
    ]
